backend:
  name: github # git-gateway
  repo: mlresearch/r0
  branch: gh-pages # Branch to update (optional; defaults to master)

local_backend: true

media_folder: 'assets/images'

collections:
  # Conference Settings
  - name: 'conference-settings'
    label: 'Conference Settings'
    files:
      # Website Settings
      - label: 'Conference Settings'
        name: 'site'
        file: '_config.yml'
        editor:
          preview: false
        fields:
          # Site Logo
          - label: "Title"
            name: "booktitle"
            widget: string
            hint: "Give the full name of the proceedings here."
          - label: "Conference short name"
            name: "shortname"
            widget: string
            hint: "Give the abbreviated name of the conference (e.g. AISTATS)."
          - label: "Start date"
            name: 'start'
            widget: 'datetime'
            format: "YYYY-MM-DD"
            date_format: "YYYY-MM-DD"
            time_format: false
            hint: "Give the first day of the conference here."
          - label: "End date"
            name: 'end'
            widget: 'datetime'
            format: "YYYY-MM-DD"
            date_format: "YYYY-MM-DD"
            time_format: false
            hint: "Give the last day of the conference here."
          - label: "Published date"
            name: 'published'
            widget: 'datetime'
            format: "YYYY-MM-DD"
            date_format: "YYYY-MM-DD"
            time_format: false
            hint: "Give the date of publication of the proceedings here."
          - label: "First published date"
            name: 'firstpublished'
            widget: 'datetime'
            format: "YYYY-MM-DD"
            date_format: "YYYY-MM-DD"
            time_format: false
            hint: "Give the date of first publication of the proceedings here (e.g. if it is a reissue of an old proceedings)."
            required: false
          - label: "Editors"
            name: editor
            widget: 'list'
            hint: "List the volume editors here."
            allow_add: true
            fields:
            - label: Family Name
              name: family
              widget: string
              required: false
            - label: Given Name
              hint: "Include initials, e.g. Neil D."
              name: given
              widget: string
              required: false
            - label: Prefix
              hint: "e.g. de, von, van"
              name: prefix
              required: false
              widget: string
            - label: Suffix
              name: suffix
              widget: string
              required: false
            - label: Consortium
              name: consortium
              hint: "Some papers are written by a consortium of authors. If that's the case for this paper use this field to fill in the consortium."
              widget: "object"
              required: false
              fields:
                - name: name
                  label: Name
                  hint: Provide the name of the consortium.
                  widget: string
                  required: false
                - name: url
                  label: Link
                  hint: Provide a URL link to the consortium.
                  widget: string
                  required: false
          - label: 'Conference description'
            name: 'description'
            widget: text
            hint: "Describe the conference, this section appears in the site dscription."
          - label: "Conference date range"
            name: date_str
            widget: string
  # Papers Collection
  - label: 'Papers'
    name: 'Papers'
    folder: '_posts'
    create: true
    slug: '{{published}}-{{title | slug}}'
    editor:
      preview: false
    fields:
      - label: 'Layout'
        name: 'layout'
        widget: "select"
        options: ["article", "inproceedings", "incollection", "techreport", "misc", "book", "proceedings"]
        hint: "For journal papers use 'article', for conference papers use 'inproceedings', for book chapters use 'incollection', for arXiv, SSRN and other tech reports use 'techreport', for books use 'book', for proceedings use 'proceedings' for others use 'misc'."
        default: "article"
      - label: 'Title'
        name: 'title'
        hint: "Title of the paper as published. Please capitalise the title."
        widget: 'string'
      - label: 'Abstract'
        name: 'abstract'
        widget: 'markdown'
        hint: "Abstract of the paper as publishied, or for books provide a synopsis."
      - label: 'Date of Publication'
        name: 'published'
        widget: 'datetime'
        format: "YYYY-MM-DD"
        date_format: "YYYY-MM-DD"
        time_format: false
      - label: "Authors"
        name: author
        widget: 'list'
        allow_add: true
        fields:
        - label: Family Name
          name: family
          widget: string
          required: false
        - label: Given Name
          hint: "Include initials, e.g. Neil D."
          name: given
          widget: string
          required: false
        - label: Prefix
          hint: "e.g. de, von, van"
          name: prefix
          required: false
          widget: string
        - label: Suffix
          name: suffix
          widget: string
          required: false
        - label: 'Person Page'
          hint: "Use this field if the author is a member of ml@cl"
          name: 'person_page'
          widget: 'relation'
          collection: 'people'
          search_fields: ["given", "family"]
          value_field: "{{slug}}"
          display_fields: ["given", "family"]
          options_length: 999
          multiple: false
          required: false          
        - label: Consortium
          name: consortium
          hint: "Some papers are written by a consortium of authors. If that's the case for this paper use this field to fill in the consortium."
          widget: "object"
          required: false
          fields:
          - name: name
            label: Name
            hint: Provide the name of the consortium.
            widget: string
            required: false
          - name: url
            label: Link
            hint: Provide a URL link to the consortium.
            widget: string
            required: false
          - label: 'Person Page'
            hint: "Use this field for memmbers of consortium from ml@cl"
            name: 'person_pages'
            widget: 'relation'
            collection: 'people'
            search_fields: ["given", "family"]
            value_field: "{{slug}}"
            display_fields: ["given", "family"]
            options_length: 999
            multiple: true
            required: false          
      - label: "Journal"
        name: journal
        hint: "The name of the journal where the paper was published (if it is an article)."
        widget: string
        required: false
      - label: "Volume"
        name: volume
        hint: "The volume number that the paper appears in."
        widget: string
        required: false
      - label: "Number"
        name: number
        hint: "The issue number that the paper appears in."
        widget: string
        required: false
      - label: "Collection/Proceedings Name"
        name: container-title
        hint: "The name of the collection or proceedings in which the paper appears."
        widget: string
        required: false
      - label: "Pages"
        name: pages
        hint: "The pages the paper is published on (if in numbers, provide as firstpage--lastpage)."
        widget: string
        required: false
      - label: "Publisher"
        name: publisher
        hint: "The name of the paper publisher (e.g. Springer)."
        widget: string
        required: false
      - label: "Address"
        name: address
        hint: "The address of the publisher (e.g. NY, USA)."
        required: false
      - label: "Paper's Publisher Website"
        hint: "Provide the full URL to the paper on the website of the publisher"
        name: "website"
        widget: "string"
        required: false
      - label: "HTML Version of Paper"
        hint: "Provide the full URL to the HTML version."
        name: "html"
        widget: "string"
        required: false
      - label: "PDF Version of Paper"
        hint: Provide the full URL to the PDF version.
        name: "pdf"
        widget: "string"
        required: false
      - label: "Link to Software"
        hint: "If there's code for the paper available somewhere provide the URL to that code."
        name: "software"
        widget: "string"
        required: false
      - label: "DOI"
        hint: "If there's a DOI (see http://doi.org) for the paper provide it here (just the id, not the URL)."
        name: "doi"
        widget: "string"
        required: false
      - label: "Open Review ID"
        hint: "If there's an Open Review version of the paper provide the id number only (not the URL)."
        name: "openreview"
        widget: "string"
        required: false
      - label: "arXiv ID"
        hint: "If there's an arxiv version of the paper provide the id number only (not the URL)."
        name: "arxiv"
        widget: "string"
        required: false
      - label: "SSRN Number"
        hint: "If there's an SSRN version of the paper provide the id number only (not the URL)."
        name: "ssrn"
        widget: "string"
        required: false
      - label: 'Featured Image'
        name: 'featured_image'
        hint: "Select an image from the paper to represent the work."
        widget: 'image'
        required: false
      - label: "Editors"
        name: editor
        widget: 'list'
        hint: "Provide the list of editors of the paper (if applicable)."
        allow_add: true
        fields:
        - label: Family Name
          name: family
          widget: string
          required: false
        - label: Given Name
          hint: "Include initials, e.g. Neil D."
          name: given
          widget: string
          required: false
        - label: Prefix
          hint: "e.g. de, von, van"
          name: prefix
          required: false
          widget: string
        - label: Suffix
          name: suffix
          widget: string
          required: false
        - label: 'Person Page'
          hint: "Use this field if the editor is a member of ml@cl"
          name: 'person_page'
          widget: 'relation'
          collection: 'people'
          search_fields: ["given", "family"]
          value_field: "{{slug}}"
          display_fields: ["given", "family"]
          multiple: false
          required: false          
        - label: Consortium
          name: consortium
          hint: "Some works may be edited by a consortium of editors. If that's the case for this paper use this field to fill in the consortium details."
          widget: "object"
          required: false
          fields:
          - name: name
            label: Name
            hint: Provide the name of the consortium.
            widget: string
            required: false
          - name: url
            label: Link
            hint: Provide a URL link to the consortium.
            widget: string
            required: false
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
        required: false
  
  # Opportunities Collection
  - label: 'Opportunities'
    name: 'opportunities'
    folder: '_opportunities/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'opportunities-single'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Excerpt'
        name: 'excerpt'
        widget: 'text'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'    
